const countryList = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'American Samoa',
    'Andorra',
    'Angola',
    'Anguilla',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia', 'Aruba',
    'Australia', 'Austria',
    'Azerbaijan', 'Bangladesh', 'Barbados',
    'Bahamas', 'Bahrain', 'Belarus', 'Belgium',
    'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia',
    'Bosnia and Herzegovina', 'Botswana', 'Brazil',
    'British Indian Ocean Territory', 'British Virgin Islands',
    'Brunei Darussalam', 'Bulgaria', 'Burkina Faso', 'Burma', 'Burundi',
    'Cambodia', 'Cameroon', 'Canada', 'Cape Verde', 'Cayman Islands',
    'Central African Republic', 'Chad', 'Chile', 'China', 'Christmas Island',
    'Cocos (Keeling) Islands', 'Colombia', 'Comoros', 'Congo-Brazzaville',
    'Congo-Kinshasa', 'Cook Islands', 'Costa Rica', 'Croatia', 'Cura?ao', 'Cyprus',
    'Czech Republic', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic',
    'East Timor', 'Ecuador', 'El Salvador', 'Egypt', 'Equatorial Guinea', 'Eritrea',
    'Estonia', 'Ethiopia', 'Falkland Islands', 'Faroe Islands', 'Federated States of Micronesia',
    'Fiji', 'Finland', 'France', 'French Guiana', 'French Polynesia', 'French Southern Lands',
    'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada',
    'Guadeloupe', 'Guam', 'Guatemala', 'Guernsey', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti',
    'Heard and McDonald Islands', 'Honduras', 'Hong Kong', 'Hungary', 'Iceland', 'India',
    'Indonesia', 'Iraq', 'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica',
    'Japan', 'Jersey', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait',
    'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
    'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macau', 'Macedonia', 'Madagascar',
    'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands',
    'Martinique', 'Mauritania', 'Mauritius', 'Mayotte', 'Mexico',
    'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Montserrat',
    'Morocco', 'Mozambique', 'Namibia', 'Nauru', 'Nepal',
    'Netherlands', 'New Caledonia', 'New Zealand', 'Nicaragua',
    'Niger', 'Nigeria', 'Niue', 'Norfolk Island', 'Northern Mariana Islands',
    'Norway', 'Oman', 'Pakistan', 'Palau', 'Panama', 'Papua New Guinea',
    'Paraguay', 'Peru', 'Philippines', 'Pitcairn Islands', 'Poland',
    'Portugal', 'Puerto Rico', 'Qatar', 'R?union', 'Romania', 'Russia',
    'Rwanda', 'Saint Barth?lemy', 'Saint Helena', 'Saint Kitts and Nevis',
    'Saint Lucia', 'Saint Martin', 'Saint Pierre and Miquelon', 'Saint Vincent',
    'Samoa', 'San Marino', 'S?o Tom? and Pr?ncipe', 'Saudi Arabia', 'Senegal',
    'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Sint Maarten', 'Slovakia',
    'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Georgia', 'South Korea',
    'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Svalbard and Jan Mayen', 'Sweden',
    'Swaziland', 'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania',
    'Thailand', 'Togo', 'Tokelau', 'Tonga', 'Trinidad and Tobago', 'Tunisia',
    'Turkey', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uganda',
    'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay',
    'Uzbekistan', 'Vanuatu', 'Vatican City', 'Vietnam', 'Venezuela', 'Wallis and Futuna',
    'Western Sahara', 'Yemen', 'Zambia', 'Zimbabwe',
    'Афганистан',
    'Албания',
    'Антарктика',
    'Алжир',
    'Американское Самоа',
    'Андора',
    'Ангола',
    'Антигуа и Барбуда',
    'Азербайджан',
    'Аргентина',
    'Австралия',
    'Австрия',
    'Багамские Острова',
    'Бахрейн',
    'Бангладеш',
    'Армения',
    'Барбадос',
    'Бельгия',
    'Бермудские Острова',
    'Бутан',
    'Боливия',
    'Босния и Герцеговина',
    'Ботсвана',
    'Остров Буве',
    'Бразилия',
    'Белиз',
    'Британская территория в Индийском океане',
    'Соломоновы Острова',
    'Британские Виргинские острова',
    'Бруней',
    'Болгария',
    'Мьянма',
    'Бурунди',
    'Белоруссия',
    'Камбоджа',
    'Камерун',
    'Канада',
    'Кабо-Верде',
    'Каймановы острова',
    'Центральноафриканская Республика',
    'Шри-Ланка',
    'Чад',
    'Чили',
    'Китайская Народная Республика',
    'Остров Рождества',
    'Кокосовые острова',
    'Колумбия',
    'Коморы',
    'Майотта',
    'Республика Конго',
    'Демократическая Республика Конго',
    'Острова Кука',
    'Коста-Рика',
    'Хорватия',
    'Куба',
    'Кипр',
    'Чехия',
    'Бенин',
    'Дания',
    'Доминика',
    'Доминиканская Республика',
    'Эквадор',
    'Сальвадор',
    'Экваториальная Гвинея',
    'Эфиопия',
    'Эритрея',
    'Эстония',
    'Фарерские острова',
    'Фолклендские острова',
    'Южная Георгия и Южные Сандвичевы острова',
    'Фиджи',
    'Финляндия',
    'Аландские острова',
    'Франция',
    'Французская Гвиана',
    'Французская Полинезия',
    'Французские Южные и Антарктические территории',
    'Джибути',
    'Габон',
    'Грузия',
    'Гамбия',
    'Палестина',
    'Германия',
    'Гана',
    'Гибралтар',
    'Кирибати',
    'Греция',
    'Гренландия',
    'Гренада',
    'Гваделупа',
    'Гуам',
    'Гватемала',
    'Гвинея',
    'Гайана',
    'Республика Гаити',
    'Остров Херд и острова Макдональд',
    'Ватикан',
    'Гондурас',
    'Гонконг',
    'Венгрия',
    'Исландия',
    'Индия',
    'Индонезия',
    'Иран',
    'Ирак',
    'Ирландия',
    'Израиль',
    'Италия',
    'Кот-д’Ивуар',
    'Ямайка',
    'Япония',
    'Казахстан',
    'Иордания',
    'Кения',
    'КНДР',
    'Республика Корея',
    'Кувейт',
    'Киргизия',
    'Лаос',
    'Ливан',
    'Лесото',
    'Латвия',
    'Либерия',
    'Ливия',
    'Лихтенштейн',
    'Литва',
    'Люксембург',
    'Макао',
    'Мадагаскар',
    'Малави',
    'Малайзия',
    'Мальдивы',
    'Мали',
    'Мальта',
    'Мартиника',
    'Мавритания',
    'Маврикий',
    'Мексика',
    'Монако',
    'Монголия',
    'Молдавия',
    'Черногория',
    'Монтсеррат',
    'Марокко',
    'Мозамбик',
    'Оман',
    'Намибия',
    'Науру',
    'Непал',
    'Нидерланды',
    'Кюрасао',
    'Аруба',
    'Синт-Мартен',
    'Бонэйр, Синт-Эстатиус и Саба',
    'Новая Каледония',
    'Вануату',
    'Новая Зеландия',
    'Никарагуа',
    'Нигер',
    'Нигерия',
    'Ниуэ',
    'Норфолк',
    'Норвегия',
    'Северные Марианские острова',
    'Внешние малые острова США',
    'Микронезия',
    'Маршалловы Острова',
    'Палау',
    'Пакистан',
    'Панама',
    'Папуа — Новая Гвинея',
    'Парагвай',
    'Перу',
    'Филиппины',
    'Острова Питкэрн',
    'Польша',
    'Португалия',
    'Гвинея-Бисау',
    'Восточный Тимор',
    'Пуэрто-Рико',
    'Катар',
    'Реюньон',
    'Румыния',
    'Россия',
    'Руанда',
    'Сен-Бартелеми',
    'Острова Святой Елены, Вознесения и Тристан-да-Кунья',
    'Сент-Китс и Невис',
    'Ангилья',
    'Сент-Люсия',
    'Сен-Мартен (Франция)',
    'Сен-Пьер и Микелон',
    'Сент-Винсент и Гренадины',
    'Сан-Марино',
    'Сан-Томе и Принсипи',
    'Саудовская Аравия',
    'Сенегал',
    'Сербия',
    'Сейшельские Острова',
    'Сьерра-Леоне',
    'Сингапур',
    'Словакия',
    'Словения',
    'Сомали',
    'Южно-Африканская Республика',
    'Зимбабве',
    'Испания',
    'Южный Судан',
    'Судан',
    'Западная Сахара',
    'Суринам',
    'Шпицберген и Ян-Майен',
    'Свазиленд',
    'Швеция',
    'Швейцария',
    'Сирия',
    'Таджикистан',
    'Таиланд',
    'Того',
    'Токелау',
    'Тонга',
    'Тринидад и Тобаго',
    'Объединённые Арабские Эмираты',
    'Тунис',
    'Турция',
    'Туркмения',
    'Теркс и Кайкос',
    'Тувалу',
    'Уганда',
    'Украина',
    'Республика Македония',
    'Египет',
    'Великобритания',
    'Гернси',
    'Джерси',
    'Остров Мэн',
    'Танзания',
    'Соединённые Штаты Америки',
    'Виргинские Острова',
    'Буркина-Фасо',
    'Уругвай',
    'Узбекистан',
    'Венесуэла',
    'Уоллис и Футуна',
    'Самоа',
    'Йемен',
    'Замбия',
];

export default countryList;